;; -*- mode: eask; lexical-binding: t -*-

(package "evil-textobj-tree-sitter"
         "0.5"
         "Provides evil textobjects using tree-sitter")

(website-url "https://github.com/meain/evil-textobj-tree-sitter")
(keywords "evil" "tree-sitter" "text-object" "convenience")

(package-file "evil-textobj-tree-sitter.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "25.1")

(development
 (depends-on "ert")
 (depends-on "package-lint")
 (depends-on "evil")
 (depends-on "tree-sitter")
 (depends-on "go-mode")
 (depends-on "tree-sitter-langs")
 (depends-on "treesit-auto"))
