#!/bin/sh

set -e

tmpdir="$(mktemp -d)"
git clone --depth 1 https://github.com/helix-editor/helix "$tmpdir"

HELIX_DIR="$tmpdir"

find $HELIX_DIR/runtime/queries -name 'textobjects.scm' |
    sed "s|$HELIX_DIR/runtime/queries/||" |
    while read -r file; do
        dir="$(dirname "$file")"
        filename="$(basename "$file")"

        mkdir -p "treesit-queries/$dir"
        # match? to match mapping is kinda hacky
        sed 's|\(@[^\.]*\)\.inside|\1.inner|g;s|\(@[^\.]*\)\.around|\1.outer|g;s|#match? @\([^ ]*\) "\([^"]*\)"|#match "\2" @\1|g;s/#eq?/#equal/g' \
            "$HELIX_DIR/runtime/queries/$file" > "treesit-queries/$dir/$filename"
    done

./scripts/append-additional-helix-queries

# method_spec was removed from upstream go grammar, but helix still uses it
sed -ibk 's|method_spec|method_elem|g' treesit-queries/go/textobjects.scm
rm treesit-queries/go/textobjects.scmbk

# function was removed from javascript/typescript grammar
sed -ibk '/^(function$/,+1d' treesit-queries/ecma/textobjects.scm
rm treesit-queries/ecma/textobjects.scmbk