name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.1
          - snapshot
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: cask/setup-cask@master
      with:
        version: snapshot
    - run: cask install
    - run: make compile
    - run: make lint
    - run: make checkdoc
    - run: make test
    - run: make test-queries
    - run: cd converter && go test -v
