name: test

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.2
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: cask/setup-cask@master
      with:
        version: snapshot
    - run: cask install
    - run: make compile
    - run: make lint
    - run: make checkdoc
    - run: make test
